apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ayan-warsame-services
  namespace: ayan-warsame
  labels:
    release: prometheus
    app: ayan-warsame-app
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
    scrapeTimeout: 10s
