apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ayan-warsame-services
  namespace: ayan-warsame
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: http
    path: /metrics
