apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ayan-warsame-app
  namespace: ayan-warsame
  labels:
    app: ayan-warsame-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  - port: http
    path: /health
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ayan-warsame-frontend
  namespace: ayan-warsame
  labels:
    app: ayan-warsame-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: http
    path: /health
    interval: 30s
    scrapeTimeout: 10s

